### PR TITLE
Implement simulators for dichromacy and anomalous trichromacy

### LINKED ISSUE #401: CVD simulation
Split from #352 (see its description for more). Figure out how much of color vision deficiency simulation is useful and practical to implement as a start.

### PR DESCRIPTION
**Pull request by Kirk-Fox**
This pull request implements the Brettel 1997 and Vienot 1999 approaches to simulating color vision deficiency as described [here](https://daltonlens.org/understanding-cvd-simulation/). For anomalous trichromacy, I still am trying to understand the Machado 2009 method, but was unable to implement it thus far. It is still possible to include it at a later date and institute it as the new default for protanomaly and deuteranomaly, due to its handling of anomalous trichromacy being much more principled than using simple linear interpolation.

I am not sure of the best way to implement tests for these new features and any help in that respect would be appreciated.

* Closes #401, by implementing simulators for dichromacy and anomalous trichromacy.

### CODE REVIEW

**Comment by Ogeon** [comment]
Thank you for looking into this and I appreciate the effort, but I'm still not sure it belongs in this library. It's one of those adjacent fields that I hesitate to include if they have a risk of growing too much. I'm not sure I can maintain it on my own, so it would have to be fine for it to stagnate without a "champion". It wouldn't be fair of me to merge it if I can't keep it going. That's why I phrased the issue as more of a research task, though I admit it's sparsely phrased.

I would be open to something relatively small, that's "write once, use forever". Say, something like the `chromatic_adaptation`, `color_difference` or `color_theory` modules, that very rarely need to grow and barely require maintenance. It could be a set of functions that generate `convert::Matrix3` matrices, for example. Otherwise, my standpoint from #352 hasn't changed much.

What's your point of view, so far?

**Comment by Ogeon** [comment]
Yeah, it's probably something that needs to be experimented with a bit. There seem to be multiple parts to it that are a bit loosely defined in Palette (especially different CIE XYZ versions), so it may be better to start identifying them first and build up to better support. `Lms` and `Matrix3` are a start, at least.

I can't promise it will be integrated, but don't let me stop you from continuing for your own project. A clear use case always helps! If you find any problems along the way, we can tackle them separately and hopefully make things easier. That's more of a bottom-up approach that may be easier than trying to get it in as one unit.

Does that sound good?

**Comment by Kirk-Fox** [comment]
Yeah, although there are other things higher on my list than more into this, so it might be a bit before I continue on it.

**Comment by Ogeon** [comment]
You should of course do what you feel like. I have no expectations. I'll close this one for now.

**Pull request closed without merging**
