### PR TITLE
Add a basic test crate for no_std

### LINKED ISSUE #139: Add a test crate for testing no_std builds
As mentioned in https://github.com/Ogeon/palette/pull/138#issuecomment-519881908, testing the `no_std` support seem to require a whole separate crate to avoid leaks from the dev dependencies. The current tests does not catch any compile errors from not having `std`, so this is necessary for knowing if that feature even works.

Also, if there is a better way, then that is of course preferred.

### PR DESCRIPTION
**Pull request by Ogeon**
It's very bare bones, but will hopefully get the job done.

Closes #139

### CODE REVIEW

**Comment by CryZe** [comment]
Whoops I missed this PR. You definitely need to build against a target that doesn't have std to properly check for it as no_std crates can depend on std crates (for whatever reason), so you don't know if all your dependencies are properly no_std unless you compile against a target that doesn't even have it.

**Comment by Ogeon** [comment]
Ouch, alright, I though it worked because it failed to compile (duplicate symbols) when I enabled std. Maybe that's not reliable enough. Do you have an example of how to do it in a better way?

**Comment by CryZe** [comment]
I guess what you have is fine, but I'd additionally also compile it for `--target thumbv6m-none-eabi` (and then probably just not execute it, unless you want to go through the effort with qemu)

**Comment by Ogeon** [comment]
I'm fine with not executing it for now. That's already how it's done here. I will try adding a test for `thumbv6m-none-eabi` too. Thanks for pointing it out!

**Pull request merged**
